Get start time API
nguyenvothuan/chrono pull request #18
Opened 2023-04-15 19:56 UTC by Hello576F726C64

This should work but I have not been able to test it in swagger as it keeps on saying anonymous objects do not have a account_set field

2023-04-16 02:25 UTC, nguyenvothuan requested changes

2023-04-16 02:25 UTC, nguyenvothuan commented on account/views.py
> +                                status=status.HTTP_200_OK)
Nice job handling these cases!

2023-04-16 02:25 UTC, nguyenvothuan commented on account/views.py
> +            user = request.user
so the reason you are getting Anonymous User maybe you didn't login correctly. Check my loom video on the previous PR for how to login with an access token.

2023-04-16 02:25 UTC, nguyenvothuan commented on account/urls.py
> +    path('GetStartTime', GetStartTime.as_view(), name = "get start time")
this should be the name of the API, check your issue for API description and make sure the pathname here matches that description.

2023-04-16 02:25 UTC, nguyenvothuan commented on account/urls.py
> +from account.views  import GetStartTime
you can do 2 imports Punch and GetStartTime in one line

2023-04-17 03:01 UTC, nguyenvothuan commented
Can you record a Loom video for a demo? Can be really helpful for others to see how your API will work.

2023-04-18 00:43 UTC, Hello576F726C64 commented
https://share.vidyard.com/watch/UokNwGCscPiQtmdSNpX8cL?

2023-04-18 02:48 UTC, nguyenvothuan commented
LGTM!

2023-04-18 02:49 UTC, nguyenvothuan approved these changes
LGTM

2023-04-18 02:58 UTC, merged