Create hoursWorked API
nguyenvothuan/chrono pull request #19
Opened 2023-04-17 03:33 UTC by mimiramita

resolves #10 
I think my code should work. However, I don't know how to add a parameter to the API in Swagger, so I tested adding the parameter by directly call the API in the url bar. Please let me know if it worked.

2023-04-18 02:50 UTC, nguyenvothuan requested changes

2023-04-18 02:50 UTC, nguyenvothuan commented on account/views.py
> +
try looking for swagger_auto_schema. This should display the swagger ui. I would recommend ChatGPT for this

2023-04-20 03:17 UTC, nguyenvothuan reviewed
LGTM at the moment. Can you please create a video to demo how your API works?

2023-04-20 03:17 UTC, nguyenvothuan commented on account/views.py
> +        manual_parameters=[date],
look great!

2023-04-20 03:28 UTC, mimiramita commented
I created a new time entry in my local database to test this out. The first part of the video is the case when the requested time entry exists. The second part is when it doesn't.

https://user-images.githubusercontent.com/111351821/233251002-b349b01c-6ea2-4dec-995e-2b580793e00b.mov

2023-04-21 02:22 UTC, nguyenvothuan commented
> I created a new time entry in my local database to test this out. The first part of the video is the case when the requested time entry exists. The second part is when it doesn't.
> 
>  Screen.Recording.2023-04-19.at.11.25.23.PM.mov

Nice job Mimi. One thing left is that `date` query is optional. This means, if we don't insert the `date` query in the URL, the server still returns a 200 status response with an array of entries of all dates in the past. If this seems to be a lot, you may want to limit the number of entries to 10 or 20, whichever fits the bandwidth. Recheck the description in #10

2023-04-24 19:13 UTC, nguyenvothuan approved these changes
lgtm

2023-04-24 19:13 UTC, nguyenvothuan commented on account/views.py
> +from drf_yasg.utils import swagger_auto_schema, APIView
wait, why are we having 2 `APIView` here? On line 6 and line 10. This would definitely cause unexpected behaviors.

2023-04-24 19:22 UTC, nguyenvothuan approved these changes

2023-04-24 19:22 UTC, merged