create GetEmployeeInfo and change HoursWorked output format
nguyenvothuan/chrono pull request #22
Opened 2023-05-01 19:41 UTC by mimiramita

I created GetEmployeeInfo and changed the HoursWorked output format by adding "status":"success.

2023-05-01 23:43 UTC, nguyenvothuan requested changes
Nice job! Just some feedback from my end. Also, after you have fixed all the stuff mentioned here, it's really nice to have a recording to show the demo of your API working properly.

2023-05-01 23:43 UTC, nguyenvothuan commented on account/views.py
> +                return Response({'status': 'success', 'Response': results}, status=status.HTTP_200_OK)
nice!

2023-05-01 23:43 UTC, nguyenvothuan commented on account/views.py
> +employee_id = openapi.Parameter('id', in_=openapi.IN_QUERY,
try to include `employee_id` inside the `GetEmployeeInfo`'s APIView if you don't plan to reuse `employee_id` anywhere else. It's just a way to not pollute the global scope with these variables.

2023-05-01 23:43 UTC, nguyenvothuan commented on account/views.py
> +        manual_parameters=[employee_id],
you can simply define `employee_id` inside this schema.

2023-05-01 23:43 UTC, nguyenvothuan commented on account/views.py
> +                if employee_account.manager == None or employee_account.manager.id != manager_id:
yh, this check makes sense

2023-05-01 23:43 UTC, nguyenvothuan commented on account/views.py
> +                return Response({'status': 'success', 'Response': {'email': employee_account.user.email, 'first_name': employee_account.user.first_name, 'last_name': employee_account.user.last_name,
As I said earlier in the prev class, you can return the whole object's data with a single serializer. Check it out. You can still compose a dictionary and return it like this, but the problem is it doesn't look that concise though. It's up to you to decide. I know finishing the task asap is the main priority so I don't want to stress this too much.

2023-05-01 23:43 UTC, nguyenvothuan commented on account/views.py
> +            employees = Account.objects.filter(manager=account)[:20]
so this is to handle the case when there is no `employee_id` passed in? Cool!

2023-05-01 23:43 UTC, nguyenvothuan commented on account/views.py
> +                        {'email': employee.user.email, 'first_name': employee.user.first_name, 'last_name': employee.user.last_name, 'company': employee.company.name})
Again, i would like to recommend using a serializer for this. Isn't it a way to learn more about Django :D?

2023-05-02 03:08 UTC, mimiramita commented
https://user-images.githubusercontent.com/111351821/235571580-7429dad3-bf49-41f7-879b-3dd4ac14ab6c.mov

2023-05-02 18:56 UTC, nguyenvothuan commented
LGTM

2023-05-02 18:56 UTC, nguyenvothuan approved these changes

2023-05-02 22:42 UTC, merged